// Canonical catalog-ID -> TMDb-ID map for the 70-film catalog.
// Generated by resolving each title against TMDb search, then hand-verified;
// pinning IDs makes enrichment deterministic and immune to wrong-title /
// year-mismatch search hits (e.g. "Independence Day (ID4)" must be 602, not a
// featurette; "Toy Story" 862; "Monty Python and the Holy Grail" 762).
export const TMDB_IDS: Record<number, number> = {
  1: 862, // Toy Story
  2: 710, // GoldenEye
  3: 63, // Twelve Monkeys
  4: 31174, // Richard III
  5: 807, // Se7en
  6: 629, // The Usual Suspects
  7: 11010, // The Postman
  8: 755, // From Dusk Till Dawn
  9: 197, // Braveheart
  10: 103, // Taxi Driver
  11: 9737, // Bad Boys
  12: 568, // Apollo 13
  13: 414, // Batman Forever
  14: 8068, // Desperado
  15: 13552, // The Doom Generation
  16: 9073, // Free Willy 2: The Adventure Home
  17: 281, // Strange Days
  18: 2292, // Clerks
  19: 20156, // Exotica
  20: 11, // Star Wars
  21: 241, // Natural Born Killers
  22: 101, // Léon: The Professional
  23: 680, // Pulp Fiction
  24: 278, // The Shawshank Redemption
  25: 9495, // The Crow
  26: 13, // Forrest Gump
  27: 8587, // The Lion King
  28: 854, // The Mask
  29: 6075, // Carlito's Way
  30: 5503, // The Fugitive
  31: 11934, // The Hudsucker Proxy
  32: 329, // Jurassic Park
  33: 78, // Blade Runner
  34: 319, // True Romance
  35: 812, // Aladdin
  36: 280, // Terminator 2: Judgment Day
  37: 581, // Dances with Wolves
  38: 274, // The Silence of the Lambs
  39: 275, // Fargo
  40: 10112, // The Aristocats
  41: 503475, // Wallace & Gromit: The Best of Aardman Animation
  42: 9802, // The Rock
  43: 664, // Twister
  44: 9879, // Striptease
  45: 602, // Independence Day
  46: 238, // The Godfather
  47: 15121, // The Sound of Music
  48: 562, // Die Hard
  49: 623, // A Fish Called Wanda
  50: 583, // Life of Brian
  51: 88, // Dirty Dancing
  52: 500, // Reservoir Dogs
  53: 792, // Platoon
  54: 402, // Basic Instinct
  55: 744, // Top Gun
  56: 2756, // The Abyss
  57: 762, // Monty Python and the Holy Grail
  58: 892, // Delicatessen
  59: 1891, // The Empire Strikes Back
  60: 85, // Raiders of the Lost Ark
  61: 68, // Brazil
  62: 679, // Aliens
  63: 429, // The Good, the Bad and the Ugly
  64: 185, // A Clockwork Orange
  65: 28, // Apocalypse Now
  66: 1892, // Return of the Jedi
  67: 769, // GoodFellas
  68: 348, // Alien
  69: 766, // Army of Darkness
  70: 539, // Psycho
};
